version: '3.8'

services:
  hostapd:
    image: jsiu/hostapd:2.11-r0
    network_mode: "host"
    restart: always
    privileged: true
    environment:
      - INTERFACE=wlo1
    volumes:
      - ./hostapd.conf:/hostapd.conf
  dnsmasq:
    image: strm/dnsmasq
    restart: always
    network_mode: "host"
    privileged: true
    volumes:
      - ./dnsmasq.conf:/etc/dnsmasq.conf
    ports: 
      - "53:53/udp"
      - "53:53/tcp"
    cap_add:
      - NET_ADMIN
    command: ["-d"]

